import { useState } from "react";
import { Trash2, Edit2, Calendar, AlertTriangle } from "lucide-react";
import { format } from "date-fns";
import type { ScheduleRule } from "@/types/custody";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Card } from "@/components/ui/card";
import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";

interface ActiveRulesListProps {
    rules: ScheduleRule[];
    onDelete: (ruleId: string) => Promise<void>;
    onEdit?: (rule: ScheduleRule) => void;
}

export function ActiveRulesList({ rules, onDelete, onEdit }: ActiveRulesListProps) {
    const [deletingId, setDeletingId] = useState<string | null>(null);

    const handleDeleteClick = (id: string) => {
        setDeletingId(id);
    };

    const confirmDelete = async () => {
        if (deletingId) {
            await onDelete(deletingId);
            setDeletingId(null);
        }
    };

    if (rules.length === 0) {
        return (
            <div className="text-center py-8 text-slate-400">
                <Calendar className="w-12 h-12 mx-auto mb-2 opacity-20" />
                <p className="text-sm">No active schedule patterns found.</p>
            </div>
        );
    }

    return (
        <>
            <ScrollArea className="h-[200px] w-full rounded-md border border-slate-100 bg-slate-50/50 p-4">
                <div className="space-y-3">
                    {rules.map((rule) => (
                        <Card key={rule.id} className="p-3 flex items-center justify-between border-slate-200 shadow-sm bg-white">
                            <div className="flex flex-col gap-1">
                                <div className="flex items-center gap-2">
                                    <span className="font-semibold text-sm text-slate-700">{rule.name}</span>
                                    {rule.config.startingParent && (
                                        <Badge variant="secondary" className="text-[10px] h-5 px-1.5">
                                            {rule.config.startingParent} Starts
                                        </Badge>
                                    )}
                                </div>
                                <span className="text-xs text-slate-500">
                                    {rule.config.startDate} - {rule.config.endDate}
                                </span>
                            </div>
                            <div className="flex items-center gap-1">
                                {onEdit && (
                                    <Button size="icon" variant="ghost" className="h-8 w-8 text-slate-400 hover:text-indigo-600" onClick={() => onEdit(rule)}>
                                        <Edit2 className="w-4 h-4" />
                                    </Button>
                                )}
                                <Button size="icon" variant="ghost" className="h-8 w-8 text-slate-400 hover:text-red-600 hover:bg-red-50" onClick={() => handleDeleteClick(rule.id)}>
                                    <Trash2 className="w-4 h-4" />
                                </Button>
                            </div>
                        </Card>
                    ))}
                </div>
            </ScrollArea>

            <AlertDialog open={!!deletingId} onOpenChange={(open) => !open && setDeletingId(null)}>
                <AlertDialogContent>
                    <AlertDialogHeader>
                        <AlertDialogTitle>Delete Schedule Pattern?</AlertDialogTitle>
                        <AlertDialogDescription className="flex flex-col gap-2">
                            <span>This action cannot be undone.</span>
                            <div className="flex items-start gap-2 p-3 bg-amber-50 text-amber-800 rounded-md text-xs font-medium border border-amber-100">
                                <AlertTriangle className="w-4 h-4 mt-0.5 shrink-0" />
                                This will remove ALL calendar entries generated by this rule. Manual edits to those days will be lost.
                            </div>
                        </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                        <AlertDialogCancel>Cancel</AlertDialogCancel>
                        <AlertDialogAction onClick={confirmDelete} className="bg-red-600 hover:bg-red-700">
                            Delete and Clear Calendar
                        </AlertDialogAction>
                    </AlertDialogFooter>
                </AlertDialogContent>
            </AlertDialog>
        </>
    );
}
